textfiles_dir: 'prompts2_ready\'
# project\chapter2\prompts\sample.txt
content:
  - title: "2. Survey of Existing Data Sources"
    type: heading
    level: 1
    text_files: ["intro.txt"] # list of text file names
    prompt_files: [] # list of prompt file names
    subsections:
      - title: "2.1. The Space of Parts of Work"
        type: heading
        level: 2
        text_files: []
        prompt_files: []
        subsections:
          - title: "2.1.1. Organisations"
            type: heading
            level: 3
            text_files: ["organisations_intro.txt"]
            prompt_files: ["organisations1.txt", "organisations2.txt"]
            subsections: []
          - title: "2.1.2. Projects"
            type: heading
            level: 3
            text_files: ["projects_intro.txt"]
            prompt_files: ["projects1.txt", "projects2.txt"]
            subsections: []
          - title: "2.1.3. Tasks"
            type: heading
            level: 3
            text_files: []
            prompt_files: ["tasks1.txt"]
            subsections: []
          - title: "2.1.4. Careers"
            type: heading
            level: 3
            text_files: []
            prompt_files: ["careers1.txt"]
            subsections: []
          - title: "2.1.5. Jobs"
            type: heading
            level: 3
            text_files: []
            prompt_files: ["jobs1.txt"]
            subsections: []
      - title: "2.2. Lenses"
        type: heading
        level: 2
        text_files: []
        prompt_files: []
        subsections:
          - title: "2.2.1. Financial"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.2.2. Government Statistics"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.2.3. Career"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.2.4. Research"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.2.5. Professional Associations, Market Analysis"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
      - title: "2.3. Values"
        type: heading
        level: 2
        text_files: []
        prompt_files: []
        subsections:
          - title: "2.3.1. Value"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.3.2. Issue"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
      - title: "2.4. Conclusion and Further Work"
        type: heading
        level: 2
        text_files: []
        prompt_files: []
        subsections:
          - title: "2.5.1. Conclusion"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []
          - title: "2.5.2. Further Work"
            type: heading
            level: 3
            text_files: []
            prompt_files: []
            subsections: []